### ISSUE TITLE
请问大佬是怎么学习写出脚本的？

### ISSUE THREAD

**Issue by yinyicao** [JieamI/jump-helper#2]

**Comment by JieamI** [comment]
本项目基于opencv的颜色空间识别和模板匹配，参考如下：

<https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.html#converting-colorspaces>
<https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_template_matching/py_template_matching.html#py-template-matching>
